### ISSUE TITLE
Does not work with latest release of Typer, 0.26.8

### ISSUE THREAD

**Issue by lpsinger** [bckohan/sphinxcontrib-typer#68]
https://github.com/fastapi/typer/pull/1410 broke this package because it renamed `STYLE_METAVAR`. Sphinx now fails with the following error:

```
AttributeError: module 'typer.rich_utils' has no attribute 'STYLE_METAVAR' 
```

This is referenced at:
https://github.com/sphinx-contrib/typer/blob/33ede850cacfe77e6c70ab3b02aad03d38605f5b/src/sphinxcontrib/typer/__init__.py#L486
